#############################################################################
# Makefile for building: TapEm.app/Contents/MacOS/TapEm
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  ../TapEm/TapEm.pro
# Template: app
# Command: /Users/thomas/V-PlaySDK/V-Play/ios/bin/qmake -o TapEm.xcodeproj/project.pbxproj ../TapEm/TapEm.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/thomas/V-PlaySDK/V-Play/ios/bin/moc
UIC       = /Users/thomas/V-PlaySDK/V-Play/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
INCPATH       = -I../TapEm -I. -I/Users/thomas/V-PlaySDK/V-Play/ios/mkspecs/common/uikit -I/Users/thomas/V-PlaySDK/V-Play/ios/include/VPlay -I/Users/thomas/V-PlaySDK/V-Play/ios/include -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtQuick -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtWidgets -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtMultimedia -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtGui -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtQml -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtWebSockets -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtNetwork -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtSql -I/Users/thomas/V-PlaySDK/V-Play/ios/include/QtCore -I. -I/Users/thomas/V-PlaySDK/V-Play/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_resources_user.cpp
compiler_rcc_make_all: qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_user.cpp
qrc_resources_user.cpp: /Users/thomas/V-PlaySDK/V-Play/ios/mkspecs/common/vplay/resources_user.qrc \
		/Users/thomas/V-PlaySDK/V-Play/ios/bin/rcc \
		/Users/thomas/V-PlaySDK/V-Play/vplay_license.key
	/Users/thomas/V-PlaySDK/V-Play/ios/bin/rcc -name resources_user /Users/thomas/V-PlaySDK/V-Play/ios/mkspecs/common/vplay/resources_user.qrc -o qrc_resources_user.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

